// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4G4i6G25C62EYHhOg32BId8PUinYhtVM',
    appId: '1:785971793347:android:47011f6330024d2ed24176',
    messagingSenderId: '785971793347',
    projectId: 'cab-booking-app-5a700',
    storageBucket: 'cab-booking-app-5a700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDefapCKYoMgZ9fJU0POTNKJSI5zUtDnMs',
    appId: '1:785971793347:ios:2814b1651e878d26d24176',
    messagingSenderId: '785971793347',
    projectId: 'cab-booking-app-5a700',
    storageBucket: 'cab-booking-app-5a700.appspot.com',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuuuW4pk9k_XKP7EL2GFGW_EpzqjQPPQ0',
    appId: '1:785971793347:web:3f75729dca556b6cd24176',
    messagingSenderId: '785971793347',
    projectId: 'cab-booking-app-5a700',
    authDomain: 'cab-booking-app-5a700.firebaseapp.com',
    storageBucket: 'cab-booking-app-5a700.appspot.com',
    measurementId: 'G-H5V9070X0Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDefapCKYoMgZ9fJU0POTNKJSI5zUtDnMs',
    appId: '1:785971793347:ios:2814b1651e878d26d24176',
    messagingSenderId: '785971793347',
    projectId: 'cab-booking-app-5a700',
    storageBucket: 'cab-booking-app-5a700.appspot.com',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuuuW4pk9k_XKP7EL2GFGW_EpzqjQPPQ0',
    appId: '1:785971793347:web:04bd53b83c64eb65d24176',
    messagingSenderId: '785971793347',
    projectId: 'cab-booking-app-5a700',
    authDomain: 'cab-booking-app-5a700.firebaseapp.com',
    storageBucket: 'cab-booking-app-5a700.appspot.com',
    measurementId: 'G-4VR809KW47',
  );

}